<a href="https://colab.research.google.com/github/AgaWoj/Machine-Learning/blob/main/PrzygotowanieDanych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# https://github.com/krakowiakpawel9/machine-learning-bootcamp/blob/master/supervised/01_basics/01_preprocessing.ipynb

## https://scikit-learn.org/stable/

### https://scikit-learn.org/stable/user_guide.html

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
sklearn.__version__

'1.2.2'

# Wygenerowanie danych

In [3]:
data = {'size': ['XL', 'L', 'M', 'L', 'M'],
        'color': ['red', 'green', 'blue', 'green', 'red'],
        'gender': ['female', 'male', 'male', 'female', 'female'],
        'price': [199.0, 89.0, 99.0, 129.0, 79.0],
        'weight': [500, 450, 300, 380, 410],
        'bought': ['yes', 'no', 'yes', 'no', 'yes']}

In [4]:
df_row = pd.DataFrame(data)
df_row

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

# Utworzenie kopii danych

In [5]:
df = df_row.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 368.0+ bytes


# Zmiana typu danych

In [7]:
for col in ['size', 'color', 'gender', 'bought']:
  df[col] = df[col].astype('category')
  # zmiana typu danych z object na category

df['weight'] = df['weight'].astype('float')
# zmiana typu danych z int na float

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 740.0 bytes


In [8]:
df.describe()

price      weight
count    5.000000    5.000000
mean   119.000000  408.000000
std     48.476799   75.299402
min     79.000000  300.000000
25%     89.000000  380.000000
50%     99.000000  410.000000
75%    129.000000  450.000000
max    199.000000  500.000000

In [9]:
df.describe().T

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [10]:
df.describe(include=['category']).T

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

# LabelEncoder

In [11]:
# przygotowanie danych do modelu uczenia maszynowego

# tej metody używam tylko przy targecie - czyli odpowiadam na pytanie czy kupi czy nie?

from sklearn.preprocessing import LabelEncoder


In [12]:
# chcę przemapować zmienną 'bought' czy ktoś kupił czy nie, tam gdzie yes to chcę 1 tam gdzie nie to 0

le = LabelEncoder()
le.fit(df['bought'])
# metoda fit dopasuje encoder do zmiennej bought
le.transform(df['bought'])

array([1, 0, 1, 0, 1])

In [13]:
le.fit_transform(df['bought'])

array([1, 0, 1, 0, 1])

In [14]:
le.classes_

array(['no', 'yes'], dtype=object)

In [15]:
# muszę to na stałę przypisać do modelu

df['bought'] = le.fit_transform(df['bought'])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [16]:
# jak chcę wrócić do pierwotnej postaci

le.inverse_transform(df['bought'])

array(['yes', 'no', 'yes', 'no', 'yes'], dtype=object)

In [17]:
# przypisanie trwale do obiektu df

df['bought'] = le.inverse_transform(df['bought'])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

# Kodowanie zmiennych objaśniających

## OneHotEncoder

In [18]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
encoder = OneHotEncoder(sparse=False)
encoder.fit(df[['size']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


OneHotEncoder(sparse=False, sparse_output=False)

In [20]:
encoder.transform(df[['size']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [21]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [22]:
encoder = OneHotEncoder(drop='first', sparse=False)
encoder.fit(df[['size']])
encoder.transform(df[['size']])

# drop first usówa pierwszą z dwóch kolumn
# mam n-1 kolumn, które zostały zakodowane

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [23]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

# Pandas get_dummies()

In [24]:
pd.get_dummies(data=df)

# funkcja get_dummies zakodowała wszystkie zmienne kategoryczne

price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0   500.0   False   False     True       False        False       True   
1   89.0   450.0    True   False    False       False         True      False   
2   99.0   300.0   False    True    False        True        False      False   
3  129.0   380.0    True   False    False       False         True      False   
4   79.0   410.0   False    True    False       False        False       True   

   gender_female  gender_male  bought_no  bought_yes  
0           True        False      False        True  
1          False         True       True       False  
2          False         True      False        True  
3           True        False       True       False  
4           True        False      False        True

In [25]:
pd.get_dummies(data=df, drop_first=True)
# usówa pierwszy

price  weight  size_M  size_XL  color_green  color_red  gender_male  \
0  199.0   500.0   False     True        False       True        False   
1   89.0   450.0   False    False         True      False         True   
2   99.0   300.0    True    False        False      False         True   
3  129.0   380.0   False    False         True      False        False   
4   79.0   410.0    True    False        False       True        False   

   bought_yes  
0        True  
1       False  
2        True  
3       False  
4        True

In [26]:
pd.get_dummies(data=df, drop_first=True, prefix='new')

price  weight  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0   500.0  False    True      False     True     False     True
1   89.0   450.0  False   False       True    False      True    False
2   99.0   300.0   True   False      False    False      True     True
3  129.0   380.0  False   False       True    False     False    False
4   79.0   410.0   True   False      False     True     False     True

In [27]:
pd.get_dummies(data=df, drop_first=True, prefix_sep='-')

price  weight  size-M  size-XL  color-green  color-red  gender-male  \
0  199.0   500.0   False     True        False       True        False   
1   89.0   450.0   False    False         True      False         True   
2   99.0   300.0    True    False        False      False         True   
3  129.0   380.0   False    False         True      False        False   
4   79.0   410.0    True    False        False       True        False   

   bought-yes  
0        True  
1       False  
2        True  
3       False  
4        True

In [28]:
# kodowanie tylko dla wybranych kolumn

pd.get_dummies(data=df, drop_first=True, columns=['size'])

color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes   False     True
1  green    male   89.0   450.0     no   False    False
2   blue    male   99.0   300.0    yes    True    False
3  green  female  129.0   380.0     no   False    False
4    red  female   79.0   410.0    yes    True    False

# Standaryzacja danych - StandardScaler

In [29]:
print(f"{df['price']}\n")
print(f"Średnia: {df['price'].mean()}")
print(f"Odchylenie standardowe: {df['price'].std():.4f}")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średnia: 119.0
Odchylenie standardowe: 48.4768


In [30]:
# standaryzacja - dlatego że rozrzut zmiennych ma znaczenie (skla nie ma znaczenia), np jedna zmienna ma wartosc 1 a inna 500 rozrzut jest duży
# i może zasłonić cechy tej z 1

# standaryzacja to cena - średnia przez odchylenie standardowe

(df['price'] - df['price'].mean()) / df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [31]:
def standardize(x):
  return (x-x.mean()) / x.std()

standardize(df['price'])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [32]:
from sklearn.preprocessing import scale

scale(df['price'])

# gotowa funkcja standaryzacji z sklearn
# wartości się tu różnią

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [34]:
from sklearn.preprocessing import StandardScaler

scale = StandardScaler()
scale.fit(df[['price']])
scale.transform(df[['price']])

# StandartScaler jest polecany do używania

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [35]:
scaler_price = StandardScaler()
df['price'] = scaler_price.fit_transform(df[['price']])
scaler_weight = StandardScaler()
df['weight'] = scaler_weight.fit_transform(df[['weight']])

# ze standaryzowane wartości wstawiam do DataFrame

In [36]:
df

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

In [37]:
# lub inny sposób

scaler = StandardScaler()

df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])
df

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

# Przygotowanie danych do modelu

In [38]:
df = df_row.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [39]:
le = LabelEncoder()


df['bought'] = le.fit_transform(df['bought'])

scaler = StandardScaler()
df[['price', 'weight']] = scaler.fit_transform(df[['price', 'weight']])

df = pd.get_dummies(data=df, drop_first=True)
df

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1   False     True        False       True   
1 -0.691898  0.623610       0   False    False         True      False   
2 -0.461266 -1.603567       1    True    False        False      False   
3  0.230633 -0.415740       0   False    False         True      False   
4 -0.922531  0.029696       1    True    False        False       True   

   gender_male  
0        False  
1         True  
2         True  
3        False  
4        False